# frozen_string_literal: true

module KairosMcp
  module SkillSets
    module Dream
      module Tools
        # dream_digest — derived narrative view over immutable L2/L1 fragments.
        #
        # Implements dream_digest_design_v0.4 (FROZEN). A digest is a DERIVED, per-topic,
        # access-bounded projection that sits BESIDE the fragments and never replaces them.
        # Synthesis content is generated by an LLM (like dream_propose): `package` builds the
        # snapshot + a contradiction-preserving directive, `write` persists the LLM output with
        # provenance, `read` returns it with staleness annotations.
        class DreamDigest < KairosMcp::Tools::BaseTool
          def name
            'dream_digest'
          end

          def description
            'Generate/read a DERIVED per-topic narrative digest over L2/L1 fragments. ' \
              'Never authoritative, never overwrites sources, preserves contradictions, ' \
              'access-bounded by its sources. Modes: package (snapshot+directive), write (persist ' \
              'LLM content with provenance), read (with staleness), list.'
          end

          def category
            :knowledge
          end

          def usecase_tags
            %w[dream digest narrative synthesis derived-view provenance staleness consolidation]
          end

          def related_tools
            %w[dream_scan dream_propose dream_archive knowledge_get context_save]
          end

          def input_schema
            {
              type: 'object',
              properties: {
                mode: {
                  type: 'string',
                  enum: %w[package write read list],
                  description: 'package (default): snapshot+directive for a topic. write: persist LLM content. read: digest+staleness. list: existing digests.'
                },
                topic: { type: 'string', description: 'Topic identifier (per-topic partition, I10).' },
                sources: {
                  type: 'array',
                  description: '[package] Explicit READ set. Each: {layer: l2|l1, session_id, name}. Fixes the citable universe (I6). Takes precedence over from_tag.',
                  items: {
                    type: 'object',
                    properties: {
                      layer: { type: 'string', enum: %w[l2 l1] },
                      session_id: { type: 'string' },
                      name: { type: 'string' }
                    },
                    required: %w[layer]
                  }
                },
                from_tag: {
                  type: 'string',
                  description: '[package] dream_scan->dream_digest wiring: resolve the citable universe (I6) as all live fragments carrying this tag. Used when sources is omitted.'
                },
                include_l1: {
                  type: 'boolean',
                  description: '[package] When using from_tag, also include L1 entries tagged with it. Default: true.'
                },
                snapshot: {
                  type: 'array',
                  description: '[write] The snapshot returned by package (the citable universe). Pass through unchanged.',
                  items: { type: 'object' }
                },
                content: { type: 'string', description: '[write] LLM-generated narrative grounded in the snapshot.' },
                directive_id: { type: 'string', description: 'Generation directive identity (I7).' }
              },
              required: []
            }
          end

          def call(arguments)
            mode = arguments['mode'] || 'package'
            digester = KairosMcp::SkillSets::Dream::Digester.new(config: load_dream_config)

            case mode
            when 'package' then call_package(digester, arguments)
            when 'write'   then call_write(digester, arguments)
            when 'read'    then call_read(digester, arguments)
            when 'list'    then text_content(JSON.pretty_generate(digests: digester.list))
            else
              text_content(JSON.pretty_generate(error: "unknown mode: #{mode}"))
            end
          rescue StandardError => e
            text_content(JSON.pretty_generate(error: e.message, backtrace: e.backtrace&.first(5)))
          end

          private

          def call_package(digester, arguments)
            topic = arguments['topic']
            return text_content(JSON.pretty_generate(error: 'package requires topic')) if topic.nil? || topic.empty?

            result = digester.package(
              topic: topic,
              sources: arguments['sources'],
              from_tag: arguments['from_tag'],
              include_l1: arguments.fetch('include_l1', true),
              directive_id: arguments['directive_id']
            )
            text_content(format_package(result))
          end

          def call_write(digester, arguments)
            # I2: writing a derived digest does not modify L2/L1; gate on L2 modify only if the
            # host enforces it, but a digest write never touches source content.
            topic = arguments['topic']
            return text_content(JSON.pretty_generate(error: 'write requires topic')) if topic.nil? || topic.empty?

            result = digester.write(
              topic: topic,
              snapshot: arguments['snapshot'] || [],
              content: arguments['content'],
              directive_id: arguments['directive_id']
            )
            record_generation_event(result, arguments['snapshot'] || [], arguments['directive_id'])
            text_content(format_write(result))
          end

          def call_read(digester, arguments)
            topic = arguments['topic']
            return text_content(JSON.pretty_generate(error: 'read requires topic')) if topic.nil? || topic.empty?

            text_content(format_read(digester.read(topic: topic)))
          end

          # I7: record the generation EVENT (the derived artifact itself need not be immutable).
          def record_generation_event(result, snapshot, directive_id)
            return unless result[:success]
            return unless defined?(KairosMcp::KairosChain::Chain)

            chain = KairosMcp::KairosChain::Chain.new
            chain.add_block([{
              type: 'dream_digest_generation',
              topic: result[:topic],
              directive_id: directive_id || result[:topic],
              output_hash: result[:output_hash],
              access_bound: result[:access_bound],
              provenance: Array(snapshot).map { |s| (s['ref'] || s[:ref]) }.compact,
              provenance_count: result[:provenance_count],
              generated_at: result[:generated_at]
            }.to_json])
          rescue StandardError => e
            warn "[DreamDigest] Failed to record to blockchain: #{e.message}"
          end

          def load_dream_config
            candidates = [dream_user_config_path, dream_template_config_path].compact
            path = candidates.find { |p| File.exist?(p) }
            return {} unless path

            YAML.safe_load(File.read(path), permitted_classes: [Symbol]) || {}
          end

          def dream_user_config_path
            if defined?(KairosMcp) && KairosMcp.respond_to?(:kairos_dir)
              File.join(KairosMcp.kairos_dir, 'skillsets', 'dream', 'config', 'dream.yml')
            else
              File.join(Dir.pwd, '.kairos', 'skillsets', 'dream', 'config', 'dream.yml')
            end
          end

          def dream_template_config_path
            File.expand_path('../../config/dream.yml', __dir__)
          end

          # ---- formatting -----------------------------------------------------------

          def format_package(r)
            lines = []
            lines << "## Dream Digest — Package (topic: #{r[:topic]})"
            lines << ""
            lines << "**Status**: #{r[:status]}"
            lines << "**Access bound**: #{r[:access_bound]} (I9)"
            lines << "**Directive id**: #{r[:directive_id]}"
            lines << "**Resolved from**: #{r[:resolved_from]}" if r[:resolved_from]
            lines << ""
            if r[:snapshot].empty?
              lines << "_No resolvable sources — nothing to digest (I4)._"
              return lines.join("\n")
            end
            lines << "### READ set / citable universe (#{r[:snapshot].size}) — I6"
            r[:snapshot].each do |s|
              lines << "- **#{s['ref']}** [#{s['layer']}] hash=`#{s['content_hash'][0, 12]}…` access=#{s['access']}"
            end
            lines << ""
            lines << "### Generation directive (give to LLM, then call mode=write with snapshot+content)"
            lines << "```"
            lines << r[:directive].strip
            lines << "```"
            lines << ""
            lines << "### Next step"
            lines << "```"
            lines << "dream_digest(mode: \"write\", topic: #{r[:topic].inspect},"
            lines << "  directive_id: #{r[:directive_id].inspect},"
            lines << "  snapshot: <the snapshot array above>, content: \"<LLM narrative>\")"
            lines << "```"
            lines.join("\n")
          end

          def format_write(r)
            lines = []
            lines << "## Dream Digest — Written (topic: #{r[:topic]})"
            lines << ""
            lines << "**Path**: #{r[:path]}"
            lines << "**Output hash**: `#{r[:output_hash]}`"
            lines << "**Provenance count**: #{r[:provenance_count]}"
            lines << "**Access bound**: #{r[:access_bound]} (I9)"
            lines << "**Generated at**: #{r[:generated_at]}"
            lines << ""
            lines << "_Derived view (I1/I8): not authoritative, regenerable, no write-back to L2/L1._"
            lines.join("\n")
          end

          def format_read(r)
            return "## Dream Digest — not found (topic: #{r[:topic]})" unless r[:found]

            lines = []
            lines << "## Dream Digest (topic: #{r[:topic]})"
            lines << ""
            stale_marker = r[:stale] ? "⚠️ STALE" : "fresh"
            lines << "**Status**: #{stale_marker}"
            lines << "**Access bound**: #{r[:access_bound]} (I9)"
            lines << "**Generated at**: #{r[:generated_at]}"
            lines << "**Provenance count**: #{r[:provenance_count]}"
            if r[:stale]
              lines << ""
              lines << "### Drifted sources (I5 — labelled, not corrected; regenerate to refresh)"
              r[:drifted].each { |d| lines << "- **#{d['ref']}**: #{d['reason']}" }
            end
            lines << ""
            lines << "---"
            lines << ""
            lines << r[:content]
            lines.join("\n")
          end
        end
      end
    end
  end
end
